// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ozonmp/com_message_api/v1/com_message_api.proto

package com_message_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Message) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Foo

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageValidationError) ErrorName() string { return "MessageValidationError" }

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageValidationError{}

// Validate checks the field values on DescribeMessageV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeMessageV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetMessageId() <= 0 {
		return DescribeMessageV1RequestValidationError{
			field:  "MessageId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribeMessageV1RequestValidationError is the validation error returned by
// DescribeMessageV1Request.Validate if the designated constraints aren't met.
type DescribeMessageV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeMessageV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeMessageV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeMessageV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeMessageV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeMessageV1RequestValidationError) ErrorName() string {
	return "DescribeMessageV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeMessageV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeMessageV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeMessageV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeMessageV1RequestValidationError{}

// Validate checks the field values on DescribeMessageV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribeMessageV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribeMessageV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribeMessageV1ResponseValidationError is the validation error returned by
// DescribeMessageV1Response.Validate if the designated constraints aren't met.
type DescribeMessageV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribeMessageV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribeMessageV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribeMessageV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribeMessageV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribeMessageV1ResponseValidationError) ErrorName() string {
	return "DescribeMessageV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribeMessageV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribeMessageV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribeMessageV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribeMessageV1ResponseValidationError{}
